### ISSUE TITLE
lock_timeout_seconds - Default value not being set

### ISSUE THREAD

**Issue by sfncook** [oysterbooks/python-consul-lock#2]
Trying to run the sample code from the README:

import consul
import consul_lock
from consul_lock import EphemeralLock

consul_client = consul.Consul()
consul_lock.defaults.consul_client = consul_client

ephemeral_lock = EphemeralLock('my/special/key', acquire_timeout_ms=500)
with ephemeral_lock.hold():
    # do dangerous stuff here
    print 'here be dragons'

... and I received this error message:

Traceback (most recent call last):
  File "test.py", line 8, in <module>
    ephemeral_lock = EphemeralLock('my/special/key', acquire_timeout_ms=500)
  File "/usr/local/lib/python2.7/dist-packages/consul_lock/lock_impl.py", line 65, in **init**
    'lock_timeout_seconds must be between 10 and 3600 to due to Consul\'s session ttl settings'
AssertionError: lock_timeout_seconds must be between 10 and 3600 to due to Consul's session ttl settings

Seems like the lock_timeout_seconds default value (listed as '180' in README) is not being set.

**Comment by kurtome** [comment]
Oh well that's awkward :smile: 
I've always been explicitly passing in a `lock_timeout_seconds` into each lock, so I never noticed. But the tests actually did catch this error (if I had been running them with CI...). I just released a `0.1.6` version on PyPi with the fix. Let me know if you have any other issues.
