### ISSUE TITLE
High volume / low latency locking is unstable

### ISSUE THREAD

**Issue by kurtome** [oysterbooks/python-consul-lock#4]
Let me preface this issue by saying it could be completely dependent on the our particular installation and usage pattern. We had 3 consul masters, a few dozen consul agents, running consul v0.5.2, and were using this to acquire about dozens of locks a minute which lasted under 2 seconds each.

The main issue we were seeing was leadership handoff between the master nodes about every 2 hours, sometimes more frequently. Which means for about 1 second there was no leader, meaning any attempt to acquire a lock would instantly fail, causing short loss of functionality for our application.

Reading more details from the [raft paper](https://ramcloud.stanford.edu/raft.pdf) and [chubby lock paper](https://www.google.com/url?sa=t&rct=j&q=&esrc=s&source=web&cd=1&cad=rja&uact=8&ved=0CB4QFjAAahUKEwiAzczk76HHAhUDez4KHbKnCfw&url=http%3A%2F%2Fresearch.google.com%2Farchive%2Fchubby-osdi06.pdf&ei=n1vKVcCBMYP2-QGyz6bgDw&usg=AFQjCNHQVBYDdvSJ-VgibUUfKkVNE8uyFw&bvm=bv.99804247,d.cWw), it seems to me that short-lived locks are not the intended use case of consul's locking API. Instead this seems to be much more useful for leader election style locks, where one master controls the resource that is being locked.

**Comment by kurtome** [comment]
For simplicity we wound up using our existing Zookeeper cluster and the [Kazoo](https://kazoo.readthedocs.org) library for locking, since this seemed to be more stable and required no additional maintenance on our part.

**Comment by armon** [comment]
@KurToMe Consul locking really isn't intended for short lived locks like this. That said, you shouldn't be experiencing such a high level of leadership churn either, and even a few dozen requests per second shouldn't have been an issue. It would be great if you could provide more details on the deployment and issues as a ticket against Consul so that we can investigate.

**Comment by kurtome** [comment]
Also worth noting, other Consul users have had issues with consul leadership election happening frequently, and it seems many performance improvements are on the roadmap for 0.6.0 https://groups.google.com/forum/#!topic/consul-tool/Yp-j7bZYkmI

**Comment by kurtome** [comment]
@armon thanks for the confirmation! 

We're not planning to dig into our Consul issues anymore at this very second just because it's working well enough for our other needs (also it's possible the increased load from our usage of this library contributed to the problem), but if we need more I'll open a ticket in the Consul project
